### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by paulhayes** [vshymanskyy/w600tool#2]
Checked out the master branch, and when running ```python w600tool.py``` I get the following error. 

```
Traceback (most recent call last):
  File "w600tool.py", line 171, in <module>
    parser.add_argument('-p', '--port',   default=getDefaultPort())
  File "w600tool.py", line 160, in getDefaultPort
    return comlist[0].device;
TypeError: 'generator' object is not subscriptable
```

installed python and libraries:
Python 3.8.6
w600tool      1.1.0
pyserial      3.0.1

**Comment by paulhayes** [comment]
Initially I was testing on the wemos fork, but this does happen on this version too.
